# Generated by Django 5.1 on 2024-09-08 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('horas_clase', models.IntegerField()),
                ('abreviatura', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.IntegerField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asignatura')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dia')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asignatura')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('start', models.DateField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('end', models.DateField(default=django.utils.timezone.now, verbose_name='fin')),
                ('dias_sin_clase', models.JSONField(blank=True, default=list, verbose_name='Días sin clase')),
                ('semanas_sin_clase', models.JSONField(blank=True, default=list, verbose_name='Semanas sin clase')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodo',
                'ordering': ('start',),
                'constraints': [models.CheckConstraint(condition=models.Q(('start__week_day', 1), _negated=True), name='check_start_not_sunday', violation_error_message='La fecha de inicio no puede ser domingo'), models.CheckConstraint(condition=models.Q(('end__week_day', 1), _negated=True), name='check_end_not_sunday', violation_error_message='La fecha de fin no puede ser domingo'), models.CheckConstraint(condition=models.Q(('start__lt', models.F('end'))), name='check_start__lt__end', violation_error_message='La fecha de inicio no puede ser mayor que la de fin'), models.UniqueConstraint(fields=('start', 'end'), name='unique_date')],
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodo'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('info', models.TextField()),
                ('disponibilidad', models.BooleanField(default=False)),
                ('asignaturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario')),
            ],
        ),
        migrations.AddField(
            model_name='dia',
            name='semana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.semana'),
        ),
    ]
