# Generated by Django 5.1 on 2024-09-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periodo',
            name='check_start_not_sunday',
        ),
        migrations.RemoveConstraint(
            model_name='periodo',
            name='check_end_not_sunday',
        ),
        migrations.RemoveConstraint(
            model_name='periodo',
            name='check_start__lt__end',
        ),
        migrations.RemoveConstraint(
            model_name='periodo',
            name='unique_date',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='end',
            field=models.DateField(verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='start',
            field=models.DateField(verbose_name='inicio'),
        ),
    ]
