# Generated by Django 5.1 on 2024-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_periodo_check_start_not_sunday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_de_carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('balance', models.JSONField(blank=True, default=list, verbose_name='Balamce')),
            ],
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
